/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrames;

import modelos.modUser;

/**
 *
 * @author jovan
 */
public class jfrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form jfrmMenu
     */
    public jfrmMenu() {
        setTitle("Menu");
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnProductInventory = new javax.swing.JButton();
        btnEmployeeCRUD = new javax.swing.JButton();
        btnCustomerCRUD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("Log Out");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 100, -1));

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, 30));

        btnSales.setText("Sales");
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        btnProductInventory.setText("Product inventory");
        btnProductInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductInventoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        btnEmployeeCRUD.setText("Employee CRUD");
        btnEmployeeCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeCRUDActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmployeeCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnCustomerCRUD.setText("Customer CRUD");
        btnCustomerCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCRUDActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomerCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        modUser.getInstance().clearSession();
        jfrmLogin loginFrame = new jfrmLogin();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        jfrmSales salesFrame = new jfrmSales(this);
        salesFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnProductInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductInventoryActionPerformed
        jfrmProductInventory productInventoryFrame = new jfrmProductInventory(this);
        productInventoryFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductInventoryActionPerformed

    private void btnEmployeeCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeCRUDActionPerformed
        jfrmEmployeeCRUD employeeCRUDFrame = new jfrmEmployeeCRUD(this);
        employeeCRUDFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeCRUDActionPerformed

    private void btnCustomerCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCRUDActionPerformed
        jfrmCustomerCRUD customerCRUDFrame = new jfrmCustomerCRUD(this);
        customerCRUDFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCustomerCRUDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerCRUD;
    private javax.swing.JButton btnEmployeeCRUD;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProductInventory;
    private javax.swing.JButton btnSales;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
